[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tek_sayac = "DDzTgmzB7rehx8DtS88B2k4uf6VNxf9zJt7Mea8FUnHG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dante/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Test ayarlarını ekliyoruz
[test]
startup_wait = 10000
validator = { url = "http://localhost:8989", command = "solana-test-validator --rpc-port 8989 --faucet-port 9901" }
